# Generated by Django 6.0.6 on 2026-06-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_url',
            field=models.URLField(blank=True, help_text='External backdrop image URL'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, help_text='External poster image URL (e.g. TMDB)'),
        ),
        migrations.AddField(
            model_name='series',
            name='backdrop_url',
            field=models.URLField(blank=True, help_text='External backdrop image URL'),
        ),
        migrations.AddField(
            model_name='series',
            name='poster_url',
            field=models.URLField(blank=True, help_text='External poster image URL (e.g. TMDB)'),
        ),
    ]
